[package]
name = "calcpi-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "calcpi_rs"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
rand = "0.8"

[build-dependencies]
cbindgen = "0.29"
